example:
  property: "I AM DEFAULT"

server:
  port: 8080

keycloak:
  uri: http://keycloak:8080


spring:
  database:
    driver-class-name: org.postgresql.Driver
  datasource:
    platform:
      postgres
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://keycloak:8080/realms/ostock
            
        registration:
          keycloak:
            client-id: ostock
            issuer-uri: http://keycloak:8080/realms/ostock
            scope:
              - openid
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ostock
          jwk-set-uri: http://keycloak:8080/realms/ostock/protocol/openid-connect/certs

            

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/

management:
  endpoint:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
