example:
  property: "I AM DEFAULT"

server:
  port: 8080

keycloak:
  uri: http://keycloak:8080


spring:
  database:
    driver-class-name: org.postgresql.Driver
  datasource:
    platform:
      postgres
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloack.uri}/realms/ostock
      client:
        registration:
          keycloak:
            client-id: ostock
            authorization-grant-type: authorization_code
            scope:
              - openid
      provider:
        keycloak:
          issuer-uri: ${keycloack.uri}/realms/ostock
          user-name-attribute: preferred_username
          

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/

management:
  endpoint:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
