server:
  port: 8081

spring:
  database:
    driver-class-name: org.postgresql.Driver
  datasource:
    platform:
      postgres
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    enabled-by-defaults: true
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/